services:
  webserver:
    image: php:8.1-apache
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html

  db:
    image: mysql:8.0
    environment:
      MYSLQ_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: myphpapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
